### ISSUE TITLE
paletteGenerator is not a function

### ISSUE THREAD

**Issue by Migaelh** [arcarson/palette-generator#4]
When use the Palette Generator in Angular i get the following error "TypeError: paletteGenerator is not a function" i did npm install and i did include it in my .ts file (like the example showed)

**Comment by arcarson** [comment]
Hi there, would you be able to post an example of your code?

**Comment by Migaelh** [comment]
import { paletteGenerator } from 'palette-generator';
 
public generate(){
      this.palette = paletteGenerator(215, "74%", "58%", {
        shadeVariation: "20%",
        hueIncrement: 15,
        scheme: "accentedAnalogous"
      })

      this.styles = {
        box: {
          backgroundColor: this.palette.alpha.base,
          borderColor: this.palette.beta.dark,
          color: this.palette.delta.lighter
        }
      } 
   }

**Comment by arcarson** [comment]
Looks like your `import` statement might be a little off.
Try:
```
import paletteGenerator from 'palette-generator';
```
instead of:
```
import { paletteGenerator } from 'palette-generator';
```
Wrapping the import item in curly braces would try an import a specific named export from the `palette-generator` module. Without the braces it imports the `defaultExport` from the module (which is what you want to be doing).

**Comment by Migaelh** [comment]
Ahh i see thank you!

**Comment by arcarson** [comment]
👍

**Comment by kirillrdy** [comment]
Also your mum says hi @arcarson
